name: Run Frontend Tests
on:
  pull_request:
    types: [ready_for_review, synchronize]
    paths:
      - "frontend/**"
jobs:
  fe-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./frontend
        run: npm i -g yarn &&  yarn install --frozen-lockfile

      - name: Sync SvelteKit
        working-directory: ./frontend
        run: yarn svelte-kit sync

      - name: Install Playwright Browsers
        working-directory: ./frontend
        run: yarn playwright install chromium --with-deps

      - name: Run Playwright tests
        env:
          PUBLIC_API_BASE_URL: "http://localhost:8000"
        working-directory: ./frontend
        run: yarn test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
